### ISSUE TITLE
Double-escaping with set_escape_uri

### ISSUE THREAD

**Issue by distobj** [openresty/set-misc-nginx-module#26]
Hi there. I'm not sure if this is a case of me not understanding what's going on, or a bug (if I were betting, I'd put money on the former :).

Scenario is an input path which contains a percent-escaped string, and I want to 301-redirect to another URL that contains that same string, still percent-escaped.

Before we found this module, our configuration was what you'd expect;

```
    location ~ /foo/(.*) {
        return 301 http://localhost/bar/$1;
    }
```

But that resulted in Location headers containing invalid URLs, as the default behaviour is that $1 apparently gets un-escaped. Example;

```
curl -I -s http://localhost/foo/100%25%20design/ | grep 'Location'
Location: http://localhost/bar/100% design/
```

So we thought set_escape_uri would help, and I built a custom nginx and tested it out. Now, we're getting doubly-escaped strings in the Location header;

```
curl -I -s http://localhost/foo/100%25%20design/ | grep 'Location'
Location: http://localhost/bar/100%2525%2520design/
```

which uses this config;

```
       location ~ /foo/(.*) {
            set_escape_uri $title $1;
            return 301 http://localhost/bar/$title;
        }
```
Any idea what's up?

**Comment by agentzh** [comment]
@distobj No, this is not a bug in this ngx_set_misc module. I won't say that this is a bug in the nginx core either.

The following snippet should work for you (tested on my side):

```nginx
    location ~ /foo/(.*) {
        set $suffix $1;
        return 301 http://localhost/bar/$suffix;
    }
```

And the following should work as well:

```nginx
    location ~ /foo/(.*) {
        set $suffix $1;
        rewrite ^ http://localhost/bar/$suffix permanent;
    }
```

In either case, you need an intermediate nginx variable to hold the value of `$1`. Why? Because `$1` is always reinitialised for ngx_rewrite module's own sake.

But yeah, the standard ngx_rewrite module could be smarter here by only wiping out existing regex captures when absolutely necessary. But this feature request should really go to the official nginx mailing list instead:

http://mailman.nginx.org/mailman/listinfo/nginx

**Comment by distobj** [comment]
Thank you for the explanation of the reinitialization, I thought that something like that might be going on. But I can also see how changing this behaviour might break a lot of existing configurations, so doubt there'll be much interest in it. Thanks again!
